name: test-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write

    steps:
      - run: make install
      - run: make lint
      - run: make test